services:
  api:
    image: ghcr.io/serious-fin/ai-solver-api:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./api/data:/app/data
    expose:
      - "8080"
  frontend:
    image: ghcr.io/serious-fin/ai-solver-web:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    expose:
      - "3000"

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data

volumes:
  caddy_data