services:
  api:
    image: seriousfin/ai-solver-api:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./api/data:/app/data
    expose:
      - "8080"
  frontend:
    image: seriousfin/ai-solver-frontend:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"