services:
  api:
    env_file: "./api/.env"
    build: ./api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./api/data:/app/data
    expose:
      - "8080"
  frontend:
    build: ./frontend
    env_file: "./frontend/.env"
    ports:
      - "80:3000"